{
    "Service": "/notificationCreator/Services/notificationCreator.service",
    "_Type": "Action.Type.OfflineOData.Upload",
    "ActionResult": {
        "_Name": "sync"
    },
    "OnSuccess": "/notificationCreator/Actions/Service/DownloadStartedMessage.action",
    "OnFailure": "/notificationCreator/Actions/Service/SyncFailureMessage.action"
}